In [16]:
import numpy as np
import cv2
car_cascade = cv2.CascadeClassifier('./cars.xml')
# eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')
img = cv2.imread('./highway.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)




In [2]:
#avoid
cars = car_cascade.detectMultiScale(gray, 1.1, 1)
for (x,y,w,h) in cars:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)


In [3]:
#avoid
cv2.imshow('video', img)
cv2.waitKey(0)


27

In [3]:
print(cars)

[[1519  170   20   20]
 [1366   77   21   21]
 [1482  292   21   21]
 [1483  554   21   21]
 [1557  555   22   22]
 [ 613   60   32   32]
 [  16  991   32   32]
 [ 430   58   43   43]
 [1500  387   39   39]
 [1009  781   41   41]
 [ 488  560   66   66]
 [1463  463   52   52]
 [   2  680   60   60]
 [1149  110  120  120]
 [ 675  304  210  210]
 [ 407  620  216  216]]


In [18]:
cap = cv2.VideoCapture("./video4.avi")
while True:
    ret, img = cap.read()
    if (type(img) == type(None)):
        break
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    cars = car_cascade.detectMultiScale(gray, 1.1, 1)

    for (x,y,w,h) in cars:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)      
    
    cv2.imshow('video', img)
    
    if cv2.waitKey(33) == 27:
        break

cv2.destroyAllWindows()


In [13]:
#https://www.youtube.com/watch?v=NpWe0Y0NUTI
cap = cv2.VideoCapture("./video3.avi")
while True:
    ret, img = cap.read()
    if (type(img) == type(None)):
        break
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    cars = car_cascade.detectMultiScale(gray, 1.1, 1)
    
    for (x,y,w,h) in cars:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
    
    cv2.imshow('video', img)
    
    if cv2.waitKey(33) == 27:
        break

cv2.destroyAllWindows()


In [22]:
cap = cv2.VideoCapture("./video5.m4v")
count = 0
while True:
    ret, img = cap.read()
    if (type(img) == type(None)):
        break
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    cars = car_cascade.detectMultiScale(gray, 1.1, 1)
    
    for (x,y,w,h) in cars:
        crop_img = img[y:y+h, x:x+w]
        cv2.imshow('video', crop_img)
        cv2.imwrite( "./images/car" + str(count) + ".bmp", crop_img);
        count += 1
        #cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
        
    #cv2.imshow('video', img)
    
    if cv2.waitKey(33) == 27:
        break

cv2.destroyAllWindows()
